/**
 * The rules of the variant, in one place. Both the in-app Rules panel and the README's
 * rules section are rendered from this array, so the two can't drift: the README block
 * between its `RULES:BEGIN`/`RULES:END` markers is generated by `rulesMarkdown()` and a
 * test fails if the file on disk no longer matches (see test/ui/rules-text.test.ts, which
 * also rewrites it when run with `UPDATE_README=1`).
 *
 * Inline markup is deliberately tiny — `**bold**`, `` `code` `` and `[text](url)` — because
 * both renderers have to understand it.
 */

export type RulesBlock =
  | { kind: 'heading'; text: string }
  | { kind: 'para'; text: string }
  | { kind: 'bullets'; items: string[] }
  | { kind: 'table'; head: string[]; rows: string[][] };

export const RULES_TITLE = 'The rules of this variant';

export const VIDEO_URL = 'https://www.youtube.com/watch?v=1ffyKPaCW5g';

export const RULES: RulesBlock[] = [
  { kind: 'heading', text: 'The variant, briefly' },
  {
    kind: 'para',
    text:
      'Standard [Diplomacy](https://en.wikipedia.org/wiki/Diplomacy_(game)) on the standard map, ' +
      'plus a step of Conway\'s Game of Life applied to the board twice a year. The variant is ' +
      'Ezio\'s, presented on DiploStrats: ' +
      `[Conway's Game of Diplomacy](${VIDEO_URL}).`,
  },
  {
    kind: 'para',
    text:
      'A year runs: **Spring Movement → Spring Retreats** (if needed) **→ Life step → Summer Spawn ' +
      'Choices** (if needed) **→ Fall Movement → Fall Retreats** (if needed) **→ Winter Builds → ' +
      'Life step → Winter Spawn Choices** (if needed). The Life step runs whether or not anything ' +
      'was dislodged or built.',
  },
  {
    kind: 'para',
    text:
      'Resolution follows the standard rules of Diplomacy — nothing about movement, support, ' +
      'convoys, retreats or adjustments is changed. It is tested against 160 cases from the DATC, ' +
      'the standard adjudication test suite, ported from the python `diplomacy` package\'s ' +
      '`test_datc.py`.',
  },

  { kind: 'heading', text: 'The Life step' },
  {
    kind: 'para',
    text:
      'A province\'s neighbours are the provinces it touches on the map — by land or by sea, and ' +
      'whether or not either unit type could actually move between them. Sea provinces count like ' +
      'any other, and a province with two coasts is one province. Every province updates ' +
      'simultaneously:',
  },
  {
    kind: 'table',
    head: ['Province', 'Occupied neighbours', 'Result'],
    rows: [
      ['occupied', '0–1', 'the unit dies (loneliness)'],
      ['occupied', '2–3', 'survives'],
      ['occupied', '4 or more', 'the unit dies (overcrowding)'],
      ['empty', 'exactly 3', 'a new unit is born'],
    ],
  },
  {
    kind: 'para',
    text:
      'A newborn unit belongs to whichever power supplied at least two of its three parents; with ' +
      'no such majority it is **neutral**.',
  },
  {
    kind: 'para',
    text:
      'Its type follows the province — fleet at sea, army inland — but on the coast it is the ' +
      'owning player\'s choice, which the GM only records. Those choices are made in the **Spawn ' +
      'Choices** phase that follows a Life step, entered and reported as build orders: ' +
      '`England: Build F Edi`. If no choice is given, the new unit is an army.',
  },

  { kind: 'heading', text: 'Neutral units' },
  {
    kind: 'bullets',
    items: [
      'They never move and are never ordered.',
      'They may receive support to hold, and they block movement and occupy their province like any unit.',
      'If dislodged, a neutral unit disbands, because it cannot submit a retreat.',
      'They never capture supply centres, and a neutral sitting on a home centre blocks a build there.',
      'They count as neighbours and as parents: two neutral parents plus one power\'s own parent ' +
        'produce a neutral birth, not a birth for that power.',
    ],
  },
  {
    kind: 'para',
    text:
      'A neutral\'s **unit type is a drawing convention, not a rule** — nothing in play can depend on ' +
      'it. At sea a neutral is drawn as a fleet, inland as an army, and on the coast the tool ' +
      'draws it as an army rather than asking.',
  },

  { kind: 'heading', text: 'Edge cases' },
  {
    kind: 'bullets',
    items: [
      '**Split-coast spawns are this tool\'s own ruling.** A fleet born on Spain, Bulgaria or ' +
        'St Petersburg also names its coast, chosen by the owning player like the unit type. The ' +
        'video never addresses which coast a split-coast spawn takes; everything else on this page ' +
        'is either stated in the video or standard Diplomacy.',
      'Life runs after Spring\'s retreats even if nothing was dislodged, and after Winter\'s ' +
        'adjustments even if nobody built. Winter\'s order is builds and removals first, then Life — ' +
        'so a fresh build can die in the same Life pass, and no spawn occurs in a province a build ' +
        'was just placed in, because that province is already occupied when Life runs.',
      'Retreats resolve before Life: a unit that successfully retreated counts at its new province ' +
        'when Life runs, and a disbanded unit no longer counts as present.',
      'Two provinces are neighbours whenever they touch on the map, whether by land or by sea, and ' +
        'whether or not the units in them could actually move between them: an army in Marseilles ' +
        'and a fleet on Spain\'s north coast are neighbours, though the fleet could never move to ' +
        'Marseilles. A province with two coasts is one province, and Switzerland is excluded, since ' +
        'it can never hold a unit.',
      'Captures happen at the standard time, between Fall retreats and Winter builds. A Summer-born ' +
        'unit sitting on a centre through Fall captures it ' +
        'that Fall like any unit; a Winter-born unit captures at the next Fall; neutrals never capture.',
      'After the Winter Life step a power\'s unit count may differ from its centre count. Nothing ' +
        'corrects that until the following Winter.',
      'Civil disorder: unordered units hold. If a power owes removals it didn\'t order, the tool ' +
        'auto-removes the units furthest from home by the standard distance-from-home rule rather ' +
        'than prompting again.',
      'Controlling 18 supply centres is generally a solo victory, although this adjudicator ' +
        'doesn\'t enforce any particular win condition.',
      'If one unit is given more than one order, the last one wins, and the tool flags the unit so ' +
        'the GM can see it happened.',
    ],
  },

  { kind: 'heading', text: 'Sharing and saving' },
  {
    kind: 'bullets',
    items: [
      'A **share link** hands anyone an independent copy of the current board — the same app, and ' +
        'nothing done there affects your game. Spawn-choice states are real board states, so they ' +
        'share too.',
      'The **offline build** (`conway-diplomacy.html`, linked in the page footer) is one HTML file ' +
        'with everything inlined; download it and open it from your own disk, with no network at all.',
      '**Export / Import JSON** saves or restores a whole game, history included.',
    ],
  },
];

// ------------------------------------------------------------------ markdown

function mdBullet(text: string): string {
  return `- ${text}`;
}

/** The README's rules section, generated from `RULES`. */
export function rulesMarkdown(): string {
  const out: string[] = [];
  for (const block of RULES) {
    switch (block.kind) {
      case 'heading':
        out.push(`## ${block.text}`);
        break;
      case 'para':
        out.push(block.text);
        break;
      case 'bullets':
        out.push(block.items.map(mdBullet).join('\n'));
        break;
      case 'table':
        out.push(
          [
            `| ${block.head.join(' | ')} |`,
            `| ${block.head.map(() => '---').join(' | ')} |`,
            ...block.rows.map((r) => `| ${r.join(' | ')} |`),
          ].join('\n'),
        );
        break;
    }
  }
  return out.join('\n\n');
}
