// Data-driven runner for the ported DATC suite (`cases.json`, generated by
// `port_datc.py` from the python `diplomacy` package's `test_datc.py`).
//
// See ./README.md for the JSON step schema and the per-phase pass/fail rules
// implemented below (they mirror the upstream `check_results`/`owner_name`/
// `check_dislodged` helpers, which are *not* a naive "does this code appear"
// check -- see the README for the VOID/OK subtleties).
//
// The suite drives parseOrders/resolveMovement/resolveRetreats/resolveAdjustments
// as exported from `src/engine/index.ts`.
import { describe, it, expect } from 'vitest';
import rawCases from './cases.json';
import { parseOrders, resolveMovement, resolveRetreats, resolveAdjustments } from '../../src/engine/index';
import { provinceOf } from '../../src/engine/map-utils';
import { STANDARD_MAP } from '../../src/data/standard-map';
import type { GameState, Order, OrderResult, Power, Season, PhaseKind, Dislodgement } from '../../src/engine/types';

// ---------- fixture schema ----------

interface UnitRef {
  type: 'A' | 'F';
  loc: string;
}

type Step =
  | { op: 'clear_units' }
  | { op: 'clear_centers' }
  | { op: 'set_units'; power: Power; units: UnitRef[] }
  | { op: 'set_centers'; power: Power; centers: string[] }
  | { op: 'set_phase'; phase: string; season: Season; year: number; kind: PhaseKind }
  | { op: 'orders'; power: Power; orders: string[] }
  | { op: 'process' }
  | { op: 'expect_owner'; unit: UnitRef; power: Power | null }
  | { op: 'expect_owned'; unit: UnitRef }
  | { op: 'expect_owner_one_of'; options: { unit: UnitRef; power: Power | null }[] }
  | { op: 'expect_dislodged'; unit: UnitRef; from: string }
  | { op: 'expect_not_dislodged'; unit: UnitRef }
  | { op: 'expect_result'; unit: UnitRef; results: OrderResult[]; phase: 'M' | 'R' | 'A'; exact: boolean };

interface Case {
  id: string;
  title: string;
  description: string;
  unsupported?: string;
  steps: Step[];
}

const cases = rawCases as Case[];

// ---------- loc / unit matching ----------

/** Province match always; coast match too, but only when `ref` specifies one. */
function locMatches(actual: string, ref: string): boolean {
  if (provinceOf(actual.toLowerCase()) !== provinceOf(ref.toLowerCase())) return false;
  return ref.includes('/') ? actual.toLowerCase() === ref.toLowerCase() : true;
}

function refStr(ref: UnitRef): string {
  return `${ref.type} ${ref.loc.toUpperCase()}`;
}

// Every order kind in Order carries a `.unit` field except `waive` (power-only,
// unused by DATC).
function orderUnitLoc(order: Order): { type: 'A' | 'F'; loc: string } | null {
  if (order.kind === 'waive') return null;
  return { type: order.unit.type, loc: order.unit.loc };
}

// ---------- case runner ----------

function findOwner(state: GameState, ref: UnitRef) {
  return state.units.find((u) => u.type === ref.type && locMatches(u.loc, ref.loc));
}

function resultsFor(results: { order: Order; result: OrderResult }[], ref: UnitRef): OrderResult[] {
  return results
    .filter((r) => {
      const u = orderUnitLoc(r.order);
      return u !== null && u.type === ref.type && locMatches(u.loc, ref.loc);
    })
    .map((r) => r.result);
}

/** Mirrors upstream `check_results`'s per-phase pass rules (see README). */
function checkResult(results: { order: Order; result: OrderResult }[], step: Extract<Step, { op: 'expect_result' }>) {
  const recorded = resultsFor(results, step.unit);
  const label = `${refStr(step.unit)} phase=${step.phase}`;

  if (step.phase === 'A' && step.exact) {
    expect(recorded, label).toEqual(step.results);
    return;
  }

  // Single-value (or, for 'A' non-exact, the one bare-VOID case) checks.
  const value = step.results[0]!;

  if (value === 'void') {
    // Void either shows up explicitly, or the unit was never validly ordered
    // this phase at all (upstream: `unit not in ordered_units`).
    expect(recorded.includes('void') || recorded.length === 0, label).toBe(true);
    return;
  }

  if (value === 'ok') {
    // OK means "no problems recorded" -- not a literal 'ok' entry.
    expect(recorded.filter((r) => r !== 'ok'), label).toEqual([]);
    return;
  }

  // bounce / cut / dislodged / disrupted / disband / no-convoy: membership.
  expect(recorded.includes(value), `${label} recorded=${JSON.stringify(recorded)}`).toBe(true);
}

function initialState(): GameState {
  const centers: GameState['centers'] = {};
  for (const [power, provinces] of Object.entries(STANDARD_MAP.startingCenters)) {
    centers[power as Power] = [...(provinces ?? [])];
  }
  return {
    version: 1,
    year: 1901,
    season: 'SPRING',
    phase: 'MOVEMENT',
    units: STANDARD_MAP.startingUnits.map((u) => ({ ...u })),
    centers,
  };
}

function runCase(c: Case) {
  let state = initialState();
  let pending: Order[] = [];
  let lastResults: { order: Order; result: OrderResult }[] = [];
  let dislodgedList: Dislodgement[] = [];

  for (const step of c.steps) {
    switch (step.op) {
      case 'clear_units':
        state = { ...state, units: [] };
        break;
      case 'clear_centers':
        state = { ...state, centers: {} };
        break;
      case 'set_units': {
        const others = state.units.filter((u) => u.power !== step.power);
        const added = step.units.map((u) => ({ power: step.power, type: u.type, loc: u.loc }));
        state = { ...state, units: [...others, ...added] };
        break;
      }
      case 'set_centers':
        state = { ...state, centers: { ...state.centers, [step.power]: [...step.centers] } };
        break;
      case 'set_phase':
        state = { ...state, season: step.season, year: step.year, phase: step.kind };
        break;
      case 'orders': {
        const text = step.orders.join('\n');
        const { orders } = parseOrders(text, state, STANDARD_MAP, step.power);
        pending = [...pending, ...orders];
        break;
      }
      case 'process': {
        if (state.phase === 'MOVEMENT') {
          const r = resolveMovement(state, pending, STANDARD_MAP);
          lastResults = r.results;
          dislodgedList = r.dislodged;
          state = r.next;
        } else if (state.phase === 'RETREAT') {
          const r = resolveRetreats(state, pending, STANDARD_MAP);
          lastResults = r.results;
          state = r.next;
          dislodgedList = [];
        } else if (state.phase === 'ADJUSTMENT') {
          const r = resolveAdjustments(state, pending, STANDARD_MAP);
          lastResults = r.results;
          state = r.next;
        } else {
          throw new Error(`don't know how to process phase ${state.phase}`);
        }
        pending = [];
        break;
      }
      case 'expect_owner': {
        const found = findOwner(state, step.unit);
        if (step.power === null) {
          expect(found, `expected ${refStr(step.unit)} to be unowned, found ${JSON.stringify(found)}`).toBeUndefined();
        } else {
          expect(found?.power, refStr(step.unit)).toBe(step.power);
        }
        break;
      }
      case 'expect_owned': {
        expect(findOwner(state, step.unit), `expected someone to own ${refStr(step.unit)}`).toBeDefined();
        break;
      }
      case 'expect_owner_one_of': {
        const ok = step.options.some((opt) => {
          const found = findOwner(state, opt.unit);
          return opt.power === null ? !found : found?.power === opt.power;
        });
        expect(ok, `expected one of ${JSON.stringify(step.options)}`).toBe(true);
        break;
      }
      case 'expect_dislodged': {
        const found = dislodgedList.find((d) => d.unit.type === step.unit.type && locMatches(d.unit.loc, step.unit.loc));
        expect(found, `expected ${refStr(step.unit)} to be dislodged`).toBeDefined();
        expect(found?.attackerFrom).toBe(step.from);
        break;
      }
      case 'expect_not_dislodged': {
        const found = dislodgedList.find((d) => d.unit.type === step.unit.type && locMatches(d.unit.loc, step.unit.loc));
        expect(found, `expected ${refStr(step.unit)} not to be dislodged`).toBeUndefined();
        break;
      }
      case 'expect_result':
        checkResult(lastResults, step);
        break;
    }
  }
}

// ---------- suite ----------

describe('DATC (ported from python diplomacy test_datc.py)', () => {
  for (const c of cases) {
    const runner = c.unsupported ? it.skip : it;
    runner(`${c.id} ${c.title}`, () => {
      runCase(c);
    });
  }
});
