import type { MapData } from '../engine/types.js';
import raw from './standard-map.json' with { type: 'json' };

/** Standard Diplomacy map. Generated by `src/data/build-standard-map.py`. */
export const STANDARD_MAP: MapData = raw as unknown as MapData;

export default STANDARD_MAP;
